In [2]:
import pandas as pd

In [12]:
# 1. Write a Python Pandas program to get the columns of the DataFrame . 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df.columns)

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'Unnamed: 24'],
      dtype='object')

In [15]:
# 2. Write a Pandas program to get the information of the DataFrame including data types and memory usage. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 25 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  50 non-null     bool
 1   belongs_to_collection  10 non-null     object
 2   budget                 50 non-null     int64
 3   genres                 50 non-null     object
 4   homepage               5 non-null      object
 5   id                     50 non-null     int64
 6   imdb_id                50 non-null     object
 7   original_language      50 non-null     object
 8   original_title         50 non-null     object
 9   overview               49 non-null     object
 10  popularity             50 non-null     object
 11  poster_path            50 non-null     object
 12  production_companies   50 non-null     object
 13  production_countries   50 non-null     object
 14  release_date           50 non-null     object
 15  revenue                50 non-null     object
 16  runtime                50 non-null     int64
 17  spoken_languages       50 non-null     object
 18  status                 50 non-null     object
 19  tagline                41 non-null     object
 20  title                  50 non-null     object
 21  video                  50 non-null     object
 22  vote_average           50 non-null     object
 23  vote_count             50 non-null     float64
 24  Unnamed: 24            1 non-null      float64
dtypes: bool(1), float64(2), int64(3), object(19)
memory usage: 9.5+ KB
None

In [18]:
# 3. Write a Pandas program to get the details of the third movie of the DataFrame 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df[2:3])

   adult                              belongs_to_collection  budget  \
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...       0

                                              genres homepage     id  \
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...      NaN  15602

     imdb_id original_language    original_title  \
2  tt0113228                en  Grumpier Old Men

                                            overview  ... revenue runtime  \
2  A family wedding reignites the ancient feud be...  ...       0     101

                           spoken_languages    status  \
2  [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                             tagline             title  video  \
2  Still Yelling. Still Fighting. Still Ready for...  Grumpier Old Men  FALSE

  vote_average vote_count Unnamed: 24
2          6.5       92.0         NaN

[1 rows x 25 columns]

In [27]:
# 4. Write a Pandas program to count the number of rows and columns of the DataFrame 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print("Number of rows:",len(df.index))
print("Number of column:",len(df.columns))

Number of rows: 50
Number of column: 25

In [30]:
# 5. Write a Pandas program to get the details of the columns title and genres of the DataFrame. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df["title"])
print(df["genres"])

0                                             Toy Story
1                                               Jumanji
2                                      Grumpier Old Men
3                                     Waiting to Exhale
4                           Father of the Bride Part II
5                                                  Heat
6                                               Sabrina
7                                          Tom and Huck
8                                          Sudden Death
9                                             GoldenEye
10                               The American President
11                          Dracula: Dead and Loving It
12                                                Balto
13                                                Nixon
14                                     Cutthroat Island
15                                               Casino
16                                Sense and Sensibility
17                                           Four Rooms
18                       Ace Ventura: When Nature Calls
19                                          Money Train
20                                           Get Shorty
21                                              Copycat
22                                            Assassins
23                                               Powder
24                                    Leaving Las Vegas
25                                              Othello
26                                         Now and Then
27                                           Persuasion
28                            The City of Lost Children
29    In 1930's Shanghai violence was not the proble...
30                                      Dangerous Minds
31                                       Twelve Monkeys
32                                     Wings of Courage
33                                                 Babe
34                                           Carrington
35                                     Dead Man Walking
36                               Across the Sea of Time
37                                         It Takes Two
38                                             Clueless
39                             Cry, the Beloved Country
40                                          Richard III
41                                      Dead Presidents
42                                          Restoration
43                                        Mortal Kombat
44                                           To Die For
45                        How To Make An American Quilt
46                                                Se7en
47                                           Pocahontas
48                                When Night Is Falling
49                                   The Usual Suspects
Name: title, dtype: object
0     [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1     [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2     [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                        [{'id': 35, 'name': 'Comedy'}]
5     [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6     [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
7     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
8     [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
9     [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
10    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
11    [{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...
12    [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
13    [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
14    [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
15    [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
16    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
17    [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
18    [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
19    [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
20    [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...
21    [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
22    [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
23    [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
24    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
25                        [{'id': 18, 'name': 'Drama'}]
26    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
27    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
28    [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...
29    [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
30    [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
31    [{'id': 878, 'name': 'Science Fiction'}, {'id'...
32    [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...
33    [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
34    [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
35                        [{'id': 18, 'name': 'Drama'}]
36    [{'id': 12, 'name': 'Adventure'}, {'id': 36, '...
37    [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...
38    [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
39                        [{'id': 18, 'name': 'Drama'}]
40    [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...
41    [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
42    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
43    [{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...
44    [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
45    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
46    [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...
47    [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
48    [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
49    [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
Name: genres, dtype: object

In [39]:
# 6. Write a Pandas program to get the details of the movie with title 'Grumpier Old Men'. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df[df["title"]=="Grumpier Old Men"])

   adult                              belongs_to_collection  budget  \
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...       0

                                              genres homepage     id  \
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...      NaN  15602

     imdb_id original_language    original_title  \
2  tt0113228                en  Grumpier Old Men

                                            overview  ... revenue runtime  \
2  A family wedding reignites the ancient feud be...  ...       0     101

                           spoken_languages    status  \
2  [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                             tagline             title  video  \
2  Still Yelling. Still Fighting. Still Ready for...  Grumpier Old Men  FALSE

  vote_average vote_count Unnamed: 24
2          6.5       92.0         NaN

[1 rows x 25 columns]

In [36]:
# 7. Write a Pandas program to get the details of  fifth movie of the DataFrame. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df[4:5])

   adult                              belongs_to_collection  budget  \
4  False  {'id': 96871, 'name': 'Father of the Bride Col...       0

                           genres homepage     id    imdb_id  \
4  [{'id': 35, 'name': 'Comedy'}]      NaN  11862  tt0113041

  original_language               original_title  \
4                en  Father of the Bride Part II

                                            overview  ...   revenue runtime  \
4  Just when George Banks has recovered from his ...  ...  76578911     106

                           spoken_languages    status  \
4  [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                             tagline  \
4  Just When His World Is Back To Normal... He's ...

                         title  video vote_average vote_count Unnamed: 24
4  Father of the Bride Part II  FALSE          5.7      173.0         NaN

[1 rows x 25 columns]

In [43]:
# 8. Write a Pandas program to create a smaller DataFrame with a subset of all features. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
subset = df[["id","title","budget","revenue","runtime"]]
print(subset)

        id                                              title    budget  \
0      862                                          Toy Story  30000000
1     8844                                            Jumanji  65000000
2    15602                                   Grumpier Old Men         0
3    31357                                  Waiting to Exhale  16000000
4    11862                        Father of the Bride Part II         0
5      949                                               Heat  60000000
6    11860                                            Sabrina  58000000
7    45325                                       Tom and Huck         0
8     9091                                       Sudden Death  35000000
9      710                                          GoldenEye  58000000
10    9087                             The American President  62000000
11   12110                        Dracula: Dead and Loving It         0
12   21032                                              Balto         0
13   10858                                              Nixon  44000000
14    1408                                   Cutthroat Island  98000000
15     524                                             Casino  52000000
16    4584                              Sense and Sensibility  16500000
17       5                                         Four Rooms   4000000
18    9273                     Ace Ventura: When Nature Calls  30000000
19   11517                                        Money Train  60000000
20    8012                                         Get Shorty  30250000
21    1710                                            Copycat         0
22    9691                                          Assassins  50000000
23   12665                                             Powder         0
24     451                                  Leaving Las Vegas   3600000
25   16420                                            Othello         0
26    9263                                       Now and Then  12000000
27   17015                                         Persuasion         0
28     902                          The City of Lost Children  18000000
29   37557  In 1930's Shanghai violence was not the proble...         0
30    9909                                    Dangerous Minds         0
31      63                                     Twelve Monkeys  29500000
32   78802                                   Wings of Courage         0
33    9598                                               Babe  30000000
34   47018                                         Carrington         0
35     687                                   Dead Man Walking  11000000
36  139405                             Across the Sea of Time         0
37   33689                                       It Takes Two         0
38    9603                                           Clueless  12000000
39   34615                           Cry, the Beloved Country         0
40   31174                                        Richard III         0
41   11443                                    Dead Presidents  10000000
42   35196                                        Restoration  19000000
43    9312                                      Mortal Kombat  18000000
44     577                                         To Die For  20000000
45   11861                      How To Make An American Quilt  10000000
46     807                                              Se7en  33000000
47   10530                                         Pocahontas  55000000
48    8391                              When Night Is Falling         0
49     629                                 The Usual Suspects   6000000

       revenue  runtime
0    373554033       81
1    262797249      104
2            0      101
3     81452156      127
4     76578911      106
5    187436818      170
6            0      127
7            0       97
8     64350171      106
9    352194034      130
10   107879496      106
11           0       88
12    11348324       78
13    13681765      192
14    10017322      119
15   116112375      178
16   135000000      136
17     4300000       98
18   212385533       90
19    35431113      103
20   115101622      105
21           0      124
22    30303072      132
23           0      111
24    49800000      112
25           0      123
26    27400000      100
27           0      104
28     1738611      108
29  30-04-1995        0
30   180000000       99
31   168840000      129
32           0       50
33   254134910       89
34           0      121
35    39363635      122
36           0       51
37           0      101
38           0       97
39      676525      106
40           0      104
41           0      119
42           0      117
43   122195920      101
44    21284514      106
45    23574130      116
46   327311859      127
47   346079773       81
48           0       96
49    23341568      106

In [46]:
# 9. Write a Pandas program to display the first 10 rows of the DataFrame. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df.head(10))

   adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1  False                                                NaN  65000000
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3  False                                                NaN  16000000
4  False  {'id': 96871, 'name': 'Father of the Bride Col...         0
5  False                                                NaN  60000000
6  False                                                NaN  58000000
7  False                                                NaN         0
8  False                                                NaN  35000000
9  False  {'id': 645, 'name': 'James Bond Collection', '...  58000000

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                     [{'id': 35, 'name': 'Comedy'}]
5  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
7  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
8  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
9  [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...

                                       homepage     id    imdb_id  \
0          http://toystory.disney.com/toy-story    862  tt0114709
1                                           NaN   8844  tt0113497
2                                           NaN  15602  tt0113228
3                                           NaN  31357  tt0114885
4                                           NaN  11862  tt0113041
5                                           NaN    949  tt0113277
6                                           NaN  11860  tt0114319
7                                           NaN  45325  tt0112302
8                                           NaN   9091  tt0114576
9  http://www.mgm.com/view/movie/757/Goldeneye/    710  tt0113189

  original_language               original_title  \
0                en                    Toy Story
1                en                      Jumanji
2                en             Grumpier Old Men
3                en            Waiting to Exhale
4                en  Father of the Bride Part II
5                en                         Heat
6                en                      Sabrina
7                en                 Tom and Huck
8                en                 Sudden Death
9                en                    GoldenEye

                                            overview  ...    revenue runtime  \
0  Led by Woody, Andy's toys live happily in his ...  ...  373554033      81
1  When siblings Judy and Peter discover an encha...  ...  262797249     104
2  A family wedding reignites the ancient feud be...  ...          0     101
3  Cheated on, mistreated and stepped on, the wom...  ...   81452156     127
4  Just when George Banks has recovered from his ...  ...   76578911     106
5  Obsessive master thief, Neil McCauley leads a ...  ...  187436818     170
6  An ugly duckling having undergone a remarkable...  ...          0     127
7  A mischievous young boy, Tom Sawyer, witnesses...  ...          0      97
8  International action superstar Jean Claude Van...  ...   64350171     106
9  James Bond must unmask the mysterious head of ...  ...  352194034     130

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released
2           [{'iso_639_1': 'en', 'name': 'English'}]  Released
3           [{'iso_639_1': 'en', 'name': 'English'}]  Released
4           [{'iso_639_1': 'en', 'name': 'English'}]  Released
5  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released
6  [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...  Released
7  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released
8           [{'iso_639_1': 'en', 'name': 'English'}]  Released
9  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released

                                             tagline  \
0                                                NaN
1          Roll the dice and unleash the excitement!
2  Still Yelling. Still Fighting. Still Ready for...
3  Friends are the people who let you be yourself...
4  Just When His World Is Back To Normal... He's ...
5                           A Los Angeles Crime Saga
6  You are cordially invited to the most surprisi...
7                             The Original Bad Boys.
8                         Terror goes into overtime.
9               No limits. No fears. No substitutes.

                         title  video vote_average vote_count Unnamed: 24
0                    Toy Story  FALSE          7.7     5415.0         NaN
1                      Jumanji  FALSE          6.9     2413.0         NaN
2             Grumpier Old Men  FALSE          6.5       92.0         NaN
3            Waiting to Exhale  FALSE          6.1       34.0         NaN
4  Father of the Bride Part II  FALSE          5.7      173.0         NaN
5                         Heat  FALSE          7.7     1886.0         NaN
6                      Sabrina  FALSE          6.2      141.0         NaN
7                 Tom and Huck  FALSE          5.4       45.0         NaN
8                 Sudden Death  FALSE          5.5      174.0         NaN
9                    GoldenEye  FALSE          6.6     1194.0         NaN

[10 rows x 25 columns]

In [55]:
# 10. Write a Pandas program to sort the DataFrame based on release_date

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
df["date"] = pd.to_datetime(df["release_date"])
print(df.sort_values(by=["date"]))

    adult                              belongs_to_collection    budget  \
29  False                                                NaN         0
48  False                                                NaN         0
28  False                                                NaN  18000000
44  False                                                NaN  20000000
22  False                                                NaN  50000000
45  False                                                NaN  10000000
41  False                                                NaN  10000000
47  False  {'id': 136214, 'name': 'Pocahontas Collection'...  55000000
33  False  {'id': 9435, 'name': 'Babe Collection', 'poste...  30000000
49  False                                                NaN   6000000
38  False                                                NaN  12000000
34  False                                                NaN         0
43  False  {'id': 9818, 'name': 'Mortal Kombat Collection...  18000000
17  False                                                NaN   4000000
46  False                                                NaN  33000000
27  False                                                NaN         0
4   False  {'id': 96871, 'name': 'Father of the Bride Col...         0
18  False  {'id': 3167, 'name': 'Ace Ventura Collection',...  30000000
20  False  {'id': 91698, 'name': 'Chili Palmer Collection...  30250000
26  False                                                NaN  12000000
36  False                                                NaN         0
23  False                                                NaN         0
24  False                                                NaN   3600000
21  False                                                NaN         0
0   False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
30  False                                                NaN         0
9   False  {'id': 645, 'name': 'James Bond Collection', '...  58000000
10  False                                                NaN  62000000
37  False                                                NaN         0
19  False                                                NaN  60000000
15  False                                                NaN  52000000
16  False                                                NaN  16500000
1   False                                                NaN  65000000
25  False                                                NaN         0
5   False                                                NaN  60000000
6   False                                                NaN  58000000
39  False                                                NaN         0
2   False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3   False                                                NaN  16000000
7   False                                                NaN         0
14  False                                                NaN  98000000
11  False                                                NaN         0
12  False  {'id': 117693, 'name': 'Balto Collection', 'po...         0
13  False                                                NaN  44000000
8   False                                                NaN  35000000
35  False                                                NaN  11000000
42  False                                                NaN  19000000
31  False                                                NaN  29500000
40  False                                                NaN         0
32  False                                                NaN         0

                                               genres  \
29  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
48  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
28  [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...
44  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
22  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
45  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
41  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
47  [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
33  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
49  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
38  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
34  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
43  [{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...
17  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
46  [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...
27  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
4                      [{'id': 35, 'name': 'Comedy'}]
18  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
20  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...
26  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
36  [{'id': 12, 'name': 'Adventure'}, {'id': 36, '...
23  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
24  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
21  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
0   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
30  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
9   [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
10  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
37  [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...
19  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
15  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
16  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
1   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
25                      [{'id': 18, 'name': 'Drama'}]
5   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6   [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
39                      [{'id': 18, 'name': 'Drama'}]
2   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
7   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
14  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
11  [{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...
12  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
13  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
8   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
35                      [{'id': 18, 'name': 'Drama'}]
42  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
31  [{'id': 878, 'name': 'Science Fiction'}, {'id'...
40  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...
32  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...

                                             homepage      id    imdb_id  \
29                                                NaN   37557  tt0115012
48                                                NaN    8391  tt0114916
28                                                NaN     902  tt0112682
44                                                NaN     577  tt0114681
22                                                NaN    9691  tt0112401
45                                                NaN   11861  tt0113347
41                                                NaN   11443  tt0112819
47                                                NaN   10530  tt0114148
33                                                NaN    9598  tt0112431
49  http://www.mgm.com/#/our-titles/2083/The-Usual...     629  tt0114814
38                                                NaN    9603  tt0112697
34                                                NaN   47018  tt0112637
43                                                NaN    9312  tt0113855
17                                                NaN       5  tt0113101
46                         http://www.sevenmovie.com/     807  tt0114369
27                                                NaN   17015  tt0114117
4                                                 NaN   11862  tt0113041
18                                                NaN    9273  tt0112281
20                                                NaN    8012  tt0113161
26                                                NaN    9263  tt0114011
36                                                NaN  139405  tt0112286
23                                                NaN   12665  tt0114168
24  http://www.mgm.com/title_title.do?title_star=L...     451  tt0113627
21                                                NaN    1710  tt0112722
0                http://toystory.disney.com/toy-story     862  tt0114709
30                                                NaN    9909  tt0112792
9        http://www.mgm.com/view/movie/757/Goldeneye/     710  tt0113189
10                                                NaN    9087  tt0112346
37                                                NaN   33689  tt0113442
19                                                NaN   11517  tt0113845
15                                                NaN     524  tt0112641
16                                                NaN    4584  tt0114388
1                                                 NaN    8844  tt0113497
25                                                NaN   16420  tt0114057
5                                                 NaN     949  tt0113277
6                                                 NaN   11860  tt0114319
39                                                NaN   34615  tt0112749
2                                                 NaN   15602  tt0113228
3                                                 NaN   31357  tt0114885
7                                                 NaN   45325  tt0112302
14                                                NaN    1408  tt0112760
11                                                NaN   12110  tt0112896
12                                                NaN   21032  tt0112453
13                                                NaN   10858  tt0113987
8                                                 NaN    9091  tt0114576
35                                                NaN     687  tt0112818
42                                                NaN   35196  tt0114272
31                                                NaN      63  tt0114746
40                                                NaN   31174  tt0114279
32                                                NaN   78802  tt0114952

   original_language                    original_title  \
29                zh                               ???
48                en             When Night Is Falling
28                fr        La Cité des Enfants Perdus
44                en                        To Die For
22                en                         Assassins
45                en     How To Make An American Quilt
41                en                   Dead Presidents
47                en                        Pocahontas
33                en                              Babe
49                en                The Usual Suspects
38                en                          Clueless
34                en                        Carrington
43                en                     Mortal Kombat
17                en                        Four Rooms
46                en                             Se7en
27                en                        Persuasion
4                 en       Father of the Bride Part II
18                en    Ace Ventura: When Nature Calls
20                en                        Get Shorty
26                en                      Now and Then
36                en            Across the Sea of Time
23                en                            Powder
24                en                 Leaving Las Vegas
21                en                           Copycat
0                 en                         Toy Story
30                en                   Dangerous Minds
9                 en                         GoldenEye
10                en            The American President
37                en                      It Takes Two
19                en                       Money Train
15                en                            Casino
16                en             Sense and Sensibility
1                 en                           Jumanji
25                en                           Othello
5                 en                              Heat
6                 en                           Sabrina
39                en          Cry, the Beloved Country
2                 en                  Grumpier Old Men
3                 en                 Waiting to Exhale
7                 en                      Tom and Huck
14                en                  Cutthroat Island
11                en       Dracula: Dead and Loving It
12                en                             Balto
13                en                             Nixon
8                 en                      Sudden Death
35                en                  Dead Man Walking
42                en                       Restoration
31                en                    Twelve Monkeys
40                en                       Richard III
32                fr  Guillaumet, les ailes du courage

                                             overview  ... runtime  \
29                                              ?????  ...     NaN
48  A prudish woman, working on tenure as a litera...  ...    96.0
28  A scientist in a surrealist society kidnaps ch...  ...   108.0
44  Susan wants to work in television and will the...  ...   106.0
22  Assassin Robert Rath arrives at a funeral to k...  ...   132.0
45  Soon-to-be-wed graduate student Finn Dodd deve...  ...   116.0
41  Depicts a heist of old bills, retired from cir...  ...   119.0
47  History comes gloriously to life in Disney's e...  ...    81.0
33  Babe is a little pig who doesn't quite know hi...  ...    89.0
49  Held in an L.A. interrogation room, Verbal Kin...  ...   106.0
38  Shallow, rich and socially successful Cher is ...  ...    97.0
34  The story of the relationship between painter ...  ...   121.0
43  For nine generations an evil sorcerer has been...  ...   101.0
17  It's Ted the Bellhop's first night on the job....  ...    98.0
46  Two homicide detectives are on a desperate hun...  ...   127.0
27  This film adaptation of Jane Austen's last nov...  ...   104.0
4   Just when George Banks has recovered from his ...  ...   106.0
18  Summoned from an ashram in Tibet, Ace finds hi...  ...    90.0
20  Chili Palmer is a Miami mobster who gets sent ...  ...   105.0
26  Waxing nostalgic about the bittersweet passage...  ...   100.0
36  A young Russian boy, Thomas Minton, travels to...  ...    51.0
23  Harassed by classmates who won't accept his sh...  ...   111.0
24  Ben Sanderson, an alcoholic Hollywood screenwr...  ...   112.0
21  An agoraphobic psychologist and a female detec...  ...   124.0
0   Led by Woody, Andy's toys live happily in his ...  ...    81.0
30  Former Marine Louanne Johnson lands a gig teac...  ...    99.0
9   James Bond must unmask the mysterious head of ...  ...   130.0
10  Widowed U.S. president Andrew Shepherd, one of...  ...   106.0
37  Identical 9-year-olds from very different back...  ...   101.0
19  A vengeful New York transit cop decides to ste...  ...   103.0
15  The life of the gambling paradise  Las Vegas ...  ...   178.0
16  Rich Mr. Dashwood dies, leaving his second wif...  ...   136.0
1   When siblings Judy and Peter discover an encha...  ...   104.0
25  The evil Iago pretends to be friend of Othello...  ...   123.0
5   Obsessive master thief, Neil McCauley leads a ...  ...   170.0
6   An ugly duckling having undergone a remarkable...  ...   127.0
39  A South-African preacher goes to search for hi...  ...   106.0
2   A family wedding reignites the ancient feud be...  ...   101.0
3   Cheated on, mistreated and stepped on, the wom...  ...   127.0
7   A mischievous young boy, Tom Sawyer, witnesses...  ...    97.0
14  Morgan Adams and her slave, William Shaw, are ...  ...   119.0
11  When a lawyer shows up at the vampire's doorst...  ...    88.0
12  An outcast half-wolf risks his life to prevent...  ...    78.0
13  An all-star cast powers this epic look at Amer...  ...   192.0
8   International action superstar Jean Claude Van...  ...   106.0
35  A justice drama based on a true story about a ...  ...   122.0
42  An aspiring young physician, Robert Merivel fo...  ...   117.0
31  In the year 2035, convict James Cole reluctant...  ...   129.0
40  Shakespeare's Play transplanted into a 1930s s...  ...   104.0
32                                                NaN  ...    50.0

                                     spoken_languages  \
29                                                108
48           [{'iso_639_1': 'en', 'name': 'English'}]
28  [{'iso_639_1': 'cn', 'name': '??? / ???'}, {'i...
44           [{'iso_639_1': 'en', 'name': 'English'}]
22  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
45           [{'iso_639_1': 'en', 'name': 'English'}]
41           [{'iso_639_1': 'en', 'name': 'English'}]
47           [{'iso_639_1': 'en', 'name': 'English'}]
33           [{'iso_639_1': 'en', 'name': 'English'}]
49  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
38  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
34           [{'iso_639_1': 'en', 'name': 'English'}]
43           [{'iso_639_1': 'en', 'name': 'English'}]
17           [{'iso_639_1': 'en', 'name': 'English'}]
46           [{'iso_639_1': 'en', 'name': 'English'}]
27           [{'iso_639_1': 'en', 'name': 'English'}]
4            [{'iso_639_1': 'en', 'name': 'English'}]
18           [{'iso_639_1': 'en', 'name': 'English'}]
20           [{'iso_639_1': 'en', 'name': 'English'}]
26           [{'iso_639_1': 'en', 'name': 'English'}]
36  [{'iso_639_1': 'ru', 'name': 'P??????'}, {'iso...
23           [{'iso_639_1': 'en', 'name': 'English'}]
24           [{'iso_639_1': 'en', 'name': 'English'}]
21  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
0            [{'iso_639_1': 'en', 'name': 'English'}]
30           [{'iso_639_1': 'en', 'name': 'English'}]
9   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
10           [{'iso_639_1': 'en', 'name': 'English'}]
37           [{'iso_639_1': 'en', 'name': 'English'}]
19           [{'iso_639_1': 'en', 'name': 'English'}]
15           [{'iso_639_1': 'en', 'name': 'English'}]
16           [{'iso_639_1': 'en', 'name': 'English'}]
1   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
25           [{'iso_639_1': 'en', 'name': 'English'}]
5   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
6   [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...
39           [{'iso_639_1': 'en', 'name': 'English'}]
2            [{'iso_639_1': 'en', 'name': 'English'}]
3            [{'iso_639_1': 'en', 'name': 'English'}]
7   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
14  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
11  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
12           [{'iso_639_1': 'en', 'name': 'English'}]
13           [{'iso_639_1': 'en', 'name': 'English'}]
8            [{'iso_639_1': 'en', 'name': 'English'}]
35           [{'iso_639_1': 'en', 'name': 'English'}]
42  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
31  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
40           [{'iso_639_1': 'en', 'name': 'English'}]
32           [{'iso_639_1': 'en', 'name': 'English'}]

                                  status  \
29  [{'iso_639_1': 'zh', 'name': '???'}]
48                              Released
28                              Released
44                              Released
22                              Released
45                              Released
41                              Released
47                              Released
33                              Released
49                              Released
38                              Released
34                              Released
43                              Released
17                              Released
46                              Released
27                              Released
4                               Released
18                              Released
20                              Released
26                              Released

In [60]:
# 11. Write a Pandas program to access those movies, released after 1995-01-01

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df[df["release_date"]>"01-01-1995"])

    adult                              belongs_to_collection    budget  \
0   False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
1   False                                                NaN  65000000
2   False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
3   False                                                NaN  16000000
4   False  {'id': 96871, 'name': 'Father of the Bride Col...         0
5   False                                                NaN  60000000
6   False                                                NaN  58000000
7   False                                                NaN         0
8   False                                                NaN  35000000
9   False  {'id': 645, 'name': 'James Bond Collection', '...  58000000
10  False                                                NaN  62000000
11  False                                                NaN         0
12  False  {'id': 117693, 'name': 'Balto Collection', 'po...         0
13  False                                                NaN  44000000
14  False                                                NaN  98000000
15  False                                                NaN  52000000
16  False                                                NaN  16500000
17  False                                                NaN   4000000
18  False  {'id': 3167, 'name': 'Ace Ventura Collection',...  30000000
19  False                                                NaN  60000000
20  False  {'id': 91698, 'name': 'Chili Palmer Collection...  30250000
21  False                                                NaN         0
22  False                                                NaN  50000000
23  False                                                NaN         0
24  False                                                NaN   3600000
25  False                                                NaN         0
26  False                                                NaN  12000000
27  False                                                NaN         0
28  False                                                NaN  18000000
29  False                                                NaN         0
30  False                                                NaN         0
31  False                                                NaN  29500000
32  False                                                NaN         0
33  False  {'id': 9435, 'name': 'Babe Collection', 'poste...  30000000
34  False                                                NaN         0
35  False                                                NaN  11000000
36  False                                                NaN         0
37  False                                                NaN         0
38  False                                                NaN  12000000
39  False                                                NaN         0
40  False                                                NaN         0
41  False                                                NaN  10000000
42  False                                                NaN  19000000
43  False  {'id': 9818, 'name': 'Mortal Kombat Collection...  18000000
44  False                                                NaN  20000000
45  False                                                NaN  10000000
46  False                                                NaN  33000000
47  False  {'id': 136214, 'name': 'Pocahontas Collection'...  55000000
48  False                                                NaN         0
49  False                                                NaN   6000000

                                               genres  \
0   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                      [{'id': 35, 'name': 'Comedy'}]
5   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
6   [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
7   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
8   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
9   [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
10  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
11  [{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...
12  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
13  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
14  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
15  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
16  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
17  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
18  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
19  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
20  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...
21  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
22  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
23  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
24  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
25                      [{'id': 18, 'name': 'Drama'}]
26  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
27  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
28  [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...
29  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
30  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
31  [{'id': 878, 'name': 'Science Fiction'}, {'id'...
32  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...
33  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
34  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
35                      [{'id': 18, 'name': 'Drama'}]
36  [{'id': 12, 'name': 'Adventure'}, {'id': 36, '...
37  [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...
38  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
39                      [{'id': 18, 'name': 'Drama'}]
40  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...
41  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
42  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
43  [{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...
44  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
45  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
46  [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...
47  [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
48  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
49  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...

                                             homepage      id    imdb_id  \
0                http://toystory.disney.com/toy-story     862  tt0114709
1                                                 NaN    8844  tt0113497
2                                                 NaN   15602  tt0113228
3                                                 NaN   31357  tt0114885
4                                                 NaN   11862  tt0113041
5                                                 NaN     949  tt0113277
6                                                 NaN   11860  tt0114319
7                                                 NaN   45325  tt0112302
8                                                 NaN    9091  tt0114576
9        http://www.mgm.com/view/movie/757/Goldeneye/     710  tt0113189
10                                                NaN    9087  tt0112346
11                                                NaN   12110  tt0112896
12                                                NaN   21032  tt0112453
13                                                NaN   10858  tt0113987
14                                                NaN    1408  tt0112760
15                                                NaN     524  tt0112641
16                                                NaN    4584  tt0114388
17                                                NaN       5  tt0113101
18                                                NaN    9273  tt0112281
19                                                NaN   11517  tt0113845
20                                                NaN    8012  tt0113161
21                                                NaN    1710  tt0112722
22                                                NaN    9691  tt0112401
23                                                NaN   12665  tt0114168
24  http://www.mgm.com/title_title.do?title_star=L...     451  tt0113627
25                                                NaN   16420  tt0114057
26                                                NaN    9263  tt0114011
27                                                NaN   17015  tt0114117
28                                                NaN     902  tt0112682
29                                                NaN   37557  tt0115012
30                                                NaN    9909  tt0112792
31                                                NaN      63  tt0114746
32                                                NaN   78802  tt0114952
33                                                NaN    9598  tt0112431
34                                                NaN   47018  tt0112637
35                                                NaN     687  tt0112818
36                                                NaN  139405  tt0112286
37                                                NaN   33689  tt0113442
38                                                NaN    9603  tt0112697
39                                                NaN   34615  tt0112749
40                                                NaN   31174  tt0114279
41                                                NaN   11443  tt0112819
42                                                NaN   35196  tt0114272
43                                                NaN    9312  tt0113855
44                                                NaN     577  tt0114681
45                                                NaN   11861  tt0113347
46                         http://www.sevenmovie.com/     807  tt0114369
47                                                NaN   10530  tt0114148
48                                                NaN    8391  tt0114916
49  http://www.mgm.com/#/our-titles/2083/The-Usual...     629  tt0114814

   original_language                    original_title  \
0                 en                         Toy Story
1                 en                           Jumanji
2                 en                  Grumpier Old Men
3                 en                 Waiting to Exhale
4                 en       Father of the Bride Part II
5                 en                              Heat
6                 en                           Sabrina
7                 en                      Tom and Huck
8                 en                      Sudden Death
9                 en                         GoldenEye
10                en            The American President
11                en       Dracula: Dead and Loving It
12                en                             Balto
13                en                             Nixon
14                en                  Cutthroat Island
15                en                            Casino
16                en             Sense and Sensibility
17                en                        Four Rooms
18                en    Ace Ventura: When Nature Calls
19                en                       Money Train
20                en                        Get Shorty
21                en                           Copycat
22                en                         Assassins
23                en                            Powder
24                en                 Leaving Las Vegas
25                en                           Othello
26                en                      Now and Then
27                en                        Persuasion
28                fr        La Cité des Enfants Perdus
29                zh                               ???
30                en                   Dangerous Minds
31                en                    Twelve Monkeys
32                fr  Guillaumet, les ailes du courage
33                en                              Babe
34                en                        Carrington
35                en                  Dead Man Walking
36                en            Across the Sea of Time
37                en                      It Takes Two
38                en                          Clueless
39                en          Cry, the Beloved Country
40                en                       Richard III
41                en                   Dead Presidents
42                en                       Restoration
43                en                     Mortal Kombat
44                en                        To Die For
45                en     How To Make An American Quilt
46                en                             Se7en
47                en                        Pocahontas
48                en             When Night Is Falling
49                en                The Usual Suspects

                                             overview  ...    revenue runtime  \
0   Led by Woody, Andy's toys live happily in his ...  ...  373554033    81.0
1   When siblings Judy and Peter discover an encha...  ...  262797249   104.0
2   A family wedding reignites the ancient feud be...  ...          0   101.0
3   Cheated on, mistreated and stepped on, the wom...  ...   81452156   127.0
4   Just when George Banks has recovered from his ...  ...   76578911   106.0
5   Obsessive master thief, Neil McCauley leads a ...  ...  187436818   170.0
6   An ugly duckling having undergone a remarkable...  ...          0   127.0
7   A mischievous young boy, Tom Sawyer, witnesses...  ...          0    97.0
8   International action superstar Jean Claude Van...  ...   64350171   106.0
9   James Bond must unmask the mysterious head of ...  ...  352194034   130.0
10  Widowed U.S. president Andrew Shepherd, one of...  ...  107879496   106.0
11  When a lawyer shows up at the vampire's doorst...  ...          0    88.0
12  An outcast half-wolf risks his life to prevent...  ...   11348324    78.0
13  An all-star cast powers this epic look at Amer...  ...   13681765   192.0
14  Morgan Adams and her slave, William Shaw, are ...  ...   10017322   119.0
15  The life of the gambling paradise  Las Vegas ...  ...  116112375   178.0
16  Rich Mr. Dashwood dies, leaving his second wif...  ...  135000000   136.0
17  It's Ted the Bellhop's first night on the job....  ...    4300000    98.0
18  Summoned from an ashram in Tibet, Ace finds hi...  ...  212385533    90.0
19  A vengeful New York transit cop decides to ste...  ...   35431113   103.0
20  Chili Palmer is a Miami mobster who gets sent ...  ...  115101622   105.0
21  An agoraphobic psychologist and a female detec...  ...          0   124.0
22  Assassin Robert Rath arrives at a funeral to k...  ...   30303072   132.0
23  Harassed by classmates who won't accept his sh...  ...          0   111.0
24  Ben Sanderson, an alcoholic Hollywood screenwr...  ...   49800000   112.0
25  The evil Iago pretends to be friend of Othello...  ...          0   123.0
26  Waxing nostalgic about the bittersweet passage...  ...   27400000   100.0
27  This film adaptation of Jane Austen's last nov...  ...          0   104.0
28  A scientist in a surrealist society kidnaps ch...  ...    1738611   108.0
29                                              ?????  ...          0     NaN
30  Former Marine Louanne Johnson lands a gig teac...  ...  180000000    99.0
31  In the year 2035, convict James Cole reluctant...  ...  168840000   129.0
32                                                NaN  ...          0    50.0
33  Babe is a little pig who doesn't quite know hi...  ...  254134910    89.0
34  The story of the relationship between painter ...  ...          0   121.0
35  A justice drama based on a true story about a ...  ...   39363635   122.0
36  A young Russian boy, Thomas Minton, travels to...  ...          0    51.0
37  Identical 9-year-olds from very different back...  ...          0   101.0
38  Shallow, rich and socially successful Cher is ...  ...          0    97.0
39  A South-African preacher goes to search for hi...  ...     676525   106.0
40  Shakespeare's Play transplanted into a 1930s s...  ...          0   104.0
41  Depicts a heist of old bills, retired from cir...  ...          0   119.0
42  An aspiring young physician, Robert Merivel fo...  ...          0   117.0
43  For nine generations an evil sorcerer has been...  ...  122195920   101.0
44  Susan wants to work in television and will the...  ...   21284514   106.0
45  Soon-to-be-wed graduate student Finn Dodd deve...  ...   23574130   116.0
46  Two homicide detectives are on a desperate hun...  ...  327311859   127.0
47  History comes gloriously to life in Disney's e...  ...  346079773    81.0
48  A prudish woman, working on tenure as a litera...  ...          0    96.0
49  Held in an L.A. interrogation room, Verbal Kin...  ...   23341568   106.0

                                     spoken_languages  \
0            [{'iso_639_1': 'en', 'name': 'English'}]
1   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
2            [{'iso_639_1': 'en', 'name': 'English'}]
3            [{'iso_639_1': 'en', 'name': 'English'}]
4            [{'iso_639_1': 'en', 'name': 'English'}]
5   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
6   [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...
7   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
8            [{'iso_639_1': 'en', 'name': 'English'}]
9   [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
10           [{'iso_639_1': 'en', 'name': 'English'}]
11  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
12           [{'iso_639_1': 'en', 'name': 'English'}]
13           [{'iso_639_1': 'en', 'name': 'English'}]
14  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
15           [{'iso_639_1': 'en', 'name': 'English'}]
16           [{'iso_639_1': 'en', 'name': 'English'}]
17           [{'iso_639_1': 'en', 'name': 'English'}]
18           [{'iso_639_1': 'en', 'name': 'English'}]
19           [{'iso_639_1': 'en', 'name': 'English'}]
20           [{'iso_639_1': 'en', 'name': 'English'}]
21  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
22  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
23           [{'iso_639_1': 'en', 'name': 'English'}]
24           [{'iso_639_1': 'en', 'name': 'English'}]
25           [{'iso_639_1': 'en', 'name': 'English'}]
26           [{'iso_639_1': 'en', 'name': 'English'}]
27           [{'iso_639_1': 'en', 'name': 'English'}]
28  [{'iso_639_1': 'cn', 'name': '??? / ???'}, {'i...
29                                                108
30           [{'iso_639_1': 'en', 'name': 'English'}]
31  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
32           [{'iso_639_1': 'en', 'name': 'English'}]
33           [{'iso_639_1': 'en', 'name': 'English'}]
34           [{'iso_639_1': 'en', 'name': 'English'}]
35           [{'iso_639_1': 'en', 'name': 'English'}]
36  [{'iso_639_1': 'ru', 'name': 'P??????'}, {'iso...
37           [{'iso_639_1': 'en', 'name': 'English'}]
38  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
39           [{'iso_639_1': 'en', 'name': 'English'}]
40           [{'iso_639_1': 'en', 'name': 'English'}]
41           [{'iso_639_1': 'en', 'name': 'English'}]
42  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
43           [{'iso_639_1': 'en', 'name': 'English'}]
44           [{'iso_639_1': 'en', 'name': 'English'}]
45           [{'iso_639_1': 'en', 'name': 'English'}]
46           [{'iso_639_1': 'en', 'name': 'English'}]
47           [{'iso_639_1': 'en', 'name': 'English'}]
48           [{'iso_639_1': 'en', 'name': 'English'}]
49  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...

                                  status  \
0                               Released
1                               Released
2                               Released
3                               Released
4                               Released
5                               Released
6                               Released

In [69]:
# 12. Write a Pandas program to sort movies on runtime in descending order. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df.sort_values(by="runtime",ascending=False))

    adult                              belongs_to_collection    budget  \
13  False                                                NaN  44000000
15  False                                                NaN  52000000
5   False                                                NaN  60000000
16  False                                                NaN  16500000
22  False                                                NaN  50000000
9   False  {'id': 645, 'name': 'James Bond Collection', '...  58000000
31  False                                                NaN  29500000
46  False                                                NaN  33000000
3   False                                                NaN  16000000
6   False                                                NaN  58000000
21  False                                                NaN         0
25  False                                                NaN         0
35  False                                                NaN  11000000
34  False                                                NaN         0
14  False                                                NaN  98000000
41  False                                                NaN  10000000
42  False                                                NaN  19000000
45  False                                                NaN  10000000
24  False                                                NaN   3600000
23  False                                                NaN         0
29  False                                                NaN         0
28  False                                                NaN  18000000
39  False                                                NaN         0
44  False                                                NaN  20000000
49  False                                                NaN   6000000
4   False  {'id': 96871, 'name': 'Father of the Bride Col...         0
8   False                                                NaN  35000000
10  False                                                NaN  62000000
20  False  {'id': 91698, 'name': 'Chili Palmer Collection...  30250000
1   False                                                NaN  65000000
40  False                                                NaN         0
27  False                                                NaN         0
19  False                                                NaN  60000000
2   False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0
43  False  {'id': 9818, 'name': 'Mortal Kombat Collection...  18000000
37  False                                                NaN         0
26  False                                                NaN  12000000
30  False                                                NaN         0
17  False                                                NaN   4000000
38  False                                                NaN  12000000
7   False                                                NaN         0
48  False                                                NaN         0
18  False  {'id': 3167, 'name': 'Ace Ventura Collection',...  30000000
33  False  {'id': 9435, 'name': 'Babe Collection', 'poste...  30000000
11  False                                                NaN         0
47  False  {'id': 136214, 'name': 'Pocahontas Collection'...  55000000
0   False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000
12  False  {'id': 117693, 'name': 'Balto Collection', 'po...         0
36  False                                                NaN         0
32  False                                                NaN         0

                                               genres  \
13  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
15  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
5   [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
16  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
22  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
9   [{'id': 12, 'name': 'Adventure'}, {'id': 28, '...
31  [{'id': 878, 'name': 'Science Fiction'}, {'id'...
46  [{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...
3   [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
6   [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
21  [{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...
25                      [{'id': 18, 'name': 'Drama'}]
35                      [{'id': 18, 'name': 'Drama'}]
34  [{'id': 36, 'name': 'History'}, {'id': 18, 'na...
14  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
41  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
42  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
45  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
24  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
23  [{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...
29  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
28  [{'id': 14, 'name': 'Fantasy'}, {'id': 878, 'n...
39                      [{'id': 18, 'name': 'Drama'}]
44  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
49  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
4                      [{'id': 35, 'name': 'Comedy'}]
8   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
10  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
20  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...
1   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
40  [{'id': 18, 'name': 'Drama'}, {'id': 10752, 'n...
27  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
19  [{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...
2   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
43  [{'id': 28, 'name': 'Action'}, {'id': 14, 'nam...
37  [{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...
26  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
30  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...
17  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
38  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
7   [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
48  [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...
18  [{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...
33  [{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...
11  [{'id': 35, 'name': 'Comedy'}, {'id': 27, 'nam...
47  [{'id': 12, 'name': 'Adventure'}, {'id': 16, '...
0   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
12  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...
36  [{'id': 12, 'name': 'Adventure'}, {'id': 36, '...
32  [{'id': 10749, 'name': 'Romance'}, {'id': 12, ...

                                             homepage      id    imdb_id  \
13                                                NaN   10858  tt0113987
15                                                NaN     524  tt0112641
5                                                 NaN     949  tt0113277
16                                                NaN    4584  tt0114388
22                                                NaN    9691  tt0112401
9        http://www.mgm.com/view/movie/757/Goldeneye/     710  tt0113189
31                                                NaN      63  tt0114746
46                         http://www.sevenmovie.com/     807  tt0114369
3                                                 NaN   31357  tt0114885
6                                                 NaN   11860  tt0114319
21                                                NaN    1710  tt0112722
25                                                NaN   16420  tt0114057
35                                                NaN     687  tt0112818
34                                                NaN   47018  tt0112637
14                                                NaN    1408  tt0112760
41                                                NaN   11443  tt0112819
42                                                NaN   35196  tt0114272
45                                                NaN   11861  tt0113347
24  http://www.mgm.com/title_title.do?title_star=L...     451  tt0113627
23                                                NaN   12665  tt0114168
29                                                NaN   37557  tt0115012
28                                                NaN     902  tt0112682
39                                                NaN   34615  tt0112749
44                                                NaN     577  tt0114681
49  http://www.mgm.com/#/our-titles/2083/The-Usual...     629  tt0114814
4                                                 NaN   11862  tt0113041
8                                                 NaN    9091  tt0114576
10                                                NaN    9087  tt0112346
20                                                NaN    8012  tt0113161
1                                                 NaN    8844  tt0113497
40                                                NaN   31174  tt0114279
27                                                NaN   17015  tt0114117
19                                                NaN   11517  tt0113845
2                                                 NaN   15602  tt0113228
43                                                NaN    9312  tt0113855
37                                                NaN   33689  tt0113442
26                                                NaN    9263  tt0114011
30                                                NaN    9909  tt0112792
17                                                NaN       5  tt0113101
38                                                NaN    9603  tt0112697
7                                                 NaN   45325  tt0112302
48                                                NaN    8391  tt0114916
18                                                NaN    9273  tt0112281
33                                                NaN    9598  tt0112431
11                                                NaN   12110  tt0112896
47                                                NaN   10530  tt0114148
0                http://toystory.disney.com/toy-story     862  tt0114709
12                                                NaN   21032  tt0112453
36                                                NaN  139405  tt0112286
32                                                NaN   78802  tt0114952

   original_language                    original_title  \
13                en                             Nixon
15                en                            Casino
5                 en                              Heat
16                en             Sense and Sensibility
22                en                         Assassins
9                 en                         GoldenEye
31                en                    Twelve Monkeys
46                en                             Se7en
3                 en                 Waiting to Exhale
6                 en                           Sabrina
21                en                           Copycat
25                en                           Othello
35                en                  Dead Man Walking
34                en                        Carrington
14                en                  Cutthroat Island
41                en                   Dead Presidents
42                en                       Restoration
45                en     How To Make An American Quilt
24                en                 Leaving Las Vegas
23                en                            Powder
29                zh                               ???
28                fr        La Cité des Enfants Perdus
39                en          Cry, the Beloved Country
44                en                        To Die For
49                en                The Usual Suspects
4                 en       Father of the Bride Part II
8                 en                      Sudden Death
10                en            The American President
20                en                        Get Shorty
1                 en                           Jumanji
40                en                       Richard III
27                en                        Persuasion
19                en                       Money Train
2                 en                  Grumpier Old Men
43                en                     Mortal Kombat
37                en                      It Takes Two
26                en                      Now and Then
30                en                   Dangerous Minds
17                en                        Four Rooms
38                en                          Clueless
7                 en                      Tom and Huck
48                en             When Night Is Falling
18                en    Ace Ventura: When Nature Calls
33                en                              Babe
11                en       Dracula: Dead and Loving It
47                en                        Pocahontas
0                 en                         Toy Story
12                en                             Balto
36                en            Across the Sea of Time
32                fr  Guillaumet, les ailes du courage

                                             overview  ...  release_date  \
13  An all-star cast powers this epic look at Amer...  ...    22-12-1995
15  The life of the gambling paradise  Las Vegas ...  ...    22-11-1995
5   Obsessive master thief, Neil McCauley leads a ...  ...    15-12-1995
16  Rich Mr. Dashwood dies, leaving his second wif...  ...    13-12-1995
22  Assassin Robert Rath arrives at a funeral to k...  ...    06-10-1995
9   James Bond must unmask the mysterious head of ...  ...    16-11-1995
31  In the year 2035, convict James Cole reluctant...  ...    29-12-1995
46  Two homicide detectives are on a desperate hun...  ...    22-09-1995
3   Cheated on, mistreated and stepped on, the wom...  ...    22-12-1995
6   An ugly duckling having undergone a remarkable...  ...    15-12-1995
21  An agoraphobic psychologist and a female detec...  ...    27-10-1995
25  The evil Iago pretends to be friend of Othello...  ...    15-12-1995
35  A justice drama based on a true story about a ...  ...    29-12-1995
34  The story of the relationship between painter ...  ...    08-11-1995
14  Morgan Adams and her slave, William Shaw, are ...  ...    22-12-1995
41  Depicts a heist of old bills, retired from cir...  ...    06-10-1995
42  An aspiring young physician, Robert Merivel fo...  ...    29-12-1995
45  Soon-to-be-wed graduate student Finn Dodd deve...  ...    06-10-1995
24  Ben Sanderson, an alcoholic Hollywood screenwr...  ...    27-10-1995
23  Harassed by classmates who won't accept his sh...  ...    27-10-1995
29  A provincial boy related to a Shanghai crime f...  ...    30-04-1995
28  A scientist in a surrealist society kidnaps ch...  ...    16-05-1995
39  A South-African preacher goes to search for hi...  ...    15-12-1995
44  Susan wants to work in television and will the...  ...    20-05-1995
49  Held in an L.A. interrogation room, Verbal Kin...  ...    19-07-1995
4   Just when George Banks has recovered from his ...  ...    10-02-1995
8   International action superstar Jean Claude Van...  ...    22-12-1995
10  Widowed U.S. president Andrew Shepherd, one of...  ...    17-11-1995
20  Chili Palmer is a Miami mobster who gets sent ...  ...    20-10-1995
1   When siblings Judy and Peter discover an encha...  ...    15-12-1995
40  Shakespeare's Play transplanted into a 1930s s...  ...    29-12-1995
27  This film adaptation of Jane Austen's last nov...  ...    27-09-1995
19  A vengeful New York transit cop decides to ste...  ...    21-11-1995
2   A family wedding reignites the ancient feud be...  ...    22-12-1995
43  For nine generations an evil sorcerer has been...  ...    18-08-1995
37  Identical 9-year-olds from very different back...  ...    17-11-1995
26  Waxing nostalgic about the bittersweet passage...  ...    20-10-1995
30  Former Marine Louanne Johnson lands a gig teac...  ...    11-08-1995
17  It's Ted the Bellhop's first night on the job....  ...    09-12-1995
38  Shallow, rich and socially successful Cher is ...  ...    19-07-1995
7   A mischievous young boy, Tom Sawyer, witnesses...  ...    22-12-1995
48  A prudish woman, working on tenure as a litera...  ...    05-05-1995
18  Summoned from an ashram in Tibet, Ace finds hi...  ...    10-11-1995
33  Babe is a little pig who doesn't quite know hi...  ...    18-07-1995
11  When a lawyer shows up at the vampire's doorst...  ...    22-12-1995
47  History comes gloriously to life in Disney's e...  ...    14-06-1995
0   Led by Woody, Andy's toys live happily in his ...  ...    30-10-1995
12  An outcast half-wolf risks his life to prevent...  ...    22-12-1995
36  A young Russian boy, Thomas Minton, travels to...  ...    20-10-1995
32                                                NaN  ...    18-09-1996

      revenue runtime                                   spoken_languages  \
13   13681765     192           [{'iso_639_1': 'en', 'name': 'English'}]
15  116112375     178           [{'iso_639_1': 'en', 'name': 'English'}]
5   187436818     170  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
16  135000000     136           [{'iso_639_1': 'en', 'name': 'English'}]
22   30303072     132  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
9   352194034     130  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
31  168840000     129  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
46  327311859     127           [{'iso_639_1': 'en', 'name': 'English'}]
3    81452156     127           [{'iso_639_1': 'en', 'name': 'English'}]
6           0     127  [{'iso_639_1': 'fr', 'name': 'Français'}, {'is...
21          0     124  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
25          0     123           [{'iso_639_1': 'en', 'name': 'English'}]
35   39363635     122           [{'iso_639_1': 'en', 'name': 'English'}]
34          0     121           [{'iso_639_1': 'en', 'name': 'English'}]
14   10017322     119  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
41          0     119           [{'iso_639_1': 'en', 'name': 'English'}]
42          0     117  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
45   23574130     116           [{'iso_639_1': 'en', 'name': 'English'}]
24   49800000     112           [{'iso_639_1': 'en', 'name': 'English'}]
23          0     111           [{'iso_639_1': 'en', 'name': 'English'}]
29          0     108               [{'iso_639_1': 'zh', 'name': '???'}]
28    1738611     108  [{'iso_639_1': 'cn', 'name': '??? / ???'}, {'i...
39     676525     106           [{'iso_639_1': 'en', 'name': 'English'}]
44   21284514     106           [{'iso_639_1': 'en', 'name': 'English'}]
49   23341568     106  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
4    76578911     106           [{'iso_639_1': 'en', 'name': 'English'}]
8    64350171     106           [{'iso_639_1': 'en', 'name': 'English'}]
10  107879496     106           [{'iso_639_1': 'en', 'name': 'English'}]
20  115101622     105           [{'iso_639_1': 'en', 'name': 'English'}]
1   262797249     104  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
40          0     104           [{'iso_639_1': 'en', 'name': 'English'}]
27          0     104           [{'iso_639_1': 'en', 'name': 'English'}]
19   35431113     103           [{'iso_639_1': 'en', 'name': 'English'}]
2           0     101           [{'iso_639_1': 'en', 'name': 'English'}]
43  122195920     101           [{'iso_639_1': 'en', 'name': 'English'}]
37          0     101           [{'iso_639_1': 'en', 'name': 'English'}]
26   27400000     100           [{'iso_639_1': 'en', 'name': 'English'}]
30  180000000      99           [{'iso_639_1': 'en', 'name': 'English'}]
17    4300000      98           [{'iso_639_1': 'en', 'name': 'English'}]
38          0      97  [{'iso_639_1': 'es', 'name': 'Español'}, {'iso...
7           0      97  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
48          0      96           [{'iso_639_1': 'en', 'name': 'English'}]
18  212385533      90           [{'iso_639_1': 'en', 'name': 'English'}]
33  254134910      89           [{'iso_639_1': 'en', 'name': 'English'}]

In [73]:
# 13. Write a Pandas program to get those movies whose revenue more than 2 million and spent less than 1 million. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
revenue_df = df[df["revenue"]>2000000]
print(revenue_df[revenue_df["budget"]<1000000])

    adult                              belongs_to_collection  budget  \
4   False  {'id': 96871, 'name': 'Father of the Bride Col...       0
12  False  {'id': 117693, 'name': 'Balto Collection', 'po...       0
30  False                                                NaN       0

                                               genres homepage     id  \
4                      [{'id': 35, 'name': 'Comedy'}]      NaN  11862
12  [{'id': 10751, 'name': 'Family'}, {'id': 16, '...      NaN  21032
30  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...      NaN   9909

      imdb_id original_language               original_title  \
4   tt0113041                en  Father of the Bride Part II
12  tt0112453                en                        Balto
30  tt0112792                en              Dangerous Minds

                                             overview  ...  release_date  \
4   Just when George Banks has recovered from his ...  ...    10-02-1995
12  An outcast half-wolf risks his life to prevent...  ...    22-12-1995
30  Former Marine Louanne Johnson lands a gig teac...  ...    11-08-1995

      revenue runtime                          spoken_languages    status  \
4    76578911     106  [{'iso_639_1': 'en', 'name': 'English'}]  Released
12   11348324      78  [{'iso_639_1': 'en', 'name': 'English'}]  Released
30  180000000      99  [{'iso_639_1': 'en', 'name': 'English'}]  Released

                                              tagline  \
4   Just When His World Is Back To Normal... He's ...
12                     Part Dog. Part Wolf. All Hero.
30    She broke the rules... and changed their lives.

                          title  video vote_average vote_count
4   Father of the Bride Part II  False          5.7        173
12                        Balto  False          7.1        423
30              Dangerous Minds  False          6.4        249

[3 rows x 24 columns]

In [84]:
# 14. Write a Pandas program to get the longest runtime and shortest runtime 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print("Longest runtime:",df["runtime"].max())
print("Shortest runtime:",df["runtime"].min())

Longest runtime: 192
Shortest runtime: 50

In [94]:
# 15. Write a Pandas program to calculate the number of votes garnered by the 70% movie. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
print(df['vote_count'].quantile(0.70))

402.69999999999993

In [93]:
# 16. Write a Pandas program to display the movies (title, runtime) longer than 30 minutes and shorter than 360 minutes. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
runtime_df = df[['title', 'runtime']]
print(runtime_df[(runtime_df['runtime'] >= 30) & (runtime_df['runtime'] <= 360)])

                             title  runtime
0                        Toy Story       81
1                          Jumanji      104
2                 Grumpier Old Men      101
3                Waiting to Exhale      127
4      Father of the Bride Part II      106
5                             Heat      170
6                          Sabrina      127
7                     Tom and Huck       97
8                     Sudden Death      106
9                        GoldenEye      130
10          The American President      106
11     Dracula: Dead and Loving It       88
12                           Balto       78
13                           Nixon      192
14                Cutthroat Island      119
15                          Casino      178
16           Sense and Sensibility      136
17                      Four Rooms       98
18  Ace Ventura: When Nature Calls       90
19                     Money Train      103
20                      Get Shorty      105
21                         Copycat      124
22                       Assassins      132
23                          Powder      111
24               Leaving Las Vegas      112
25                         Othello      123
26                    Now and Then      100
27                      Persuasion      104
28       The City of Lost Children      108
29                  Shanghai Triad      108
30                 Dangerous Minds       99
31                  Twelve Monkeys      129
32                Wings of Courage       50
33                            Babe       89
34                      Carrington      121
35                Dead Man Walking      122
36          Across the Sea of Time       51
37                    It Takes Two      101
38                        Clueless       97
39        Cry, the Beloved Country      106
40                     Richard III      104
41                 Dead Presidents      119
42                     Restoration      117
43                   Mortal Kombat      101
44                      To Die For      106
45   How To Make An American Quilt      116
46                           Se7en      127
47                      Pocahontas       81
48           When Night Is Falling       96
49              The Usual Suspects      106

In [97]:
# 17. Write a Pandas program to display the movies (title, number of votes) that received specified number of votes. 

df = pd.read_csv("movie_metadata.csv",encoding='latin-1')
n = 300
count_df = df[['title', 'vote_count']]
print(count_df[count_df['vote_count'] >= n])

                             title  vote_count
0                        Toy Story        5415
1                          Jumanji        2413
5                             Heat        1886
9                        GoldenEye        1194
12                           Balto         423
15                          Casino        1343
16           Sense and Sensibility         364
17                      Four Rooms         539
18  Ace Ventura: When Nature Calls        1128
20                      Get Shorty         305
22                       Assassins         394
24               Leaving Las Vegas         365
28       The City of Lost Children         308
31                  Twelve Monkeys        2470
33                            Babe         756
35                Dead Man Walking         350
38                        Clueless         828
43                   Mortal Kombat         452
46                           Se7en        5915
47                      Pocahontas        1509
49              The Usual Suspects        3334